version: '3.3'

services:
  psql:
    container_name: psql_horoscope_track_node
    image: postgres:14-alpine
    env_file:
      - docker-compose.env
    ports:
      - 5432:5432
    volumes:
      - psql-data:/var/lib/postgresql/data
      - ./docker/psql/init.sh:/docker-entrypoint-initdb.d/init.sh
  redis:
    container_name: redis_horoscope_track_node
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  hasura:
    container_name: hasura_horoscope_track_node
    depends_on:
      - psql
    restart: always
    image: hasura/graphql-engine:v2.12.1
    ports:
      - 8080:8080
    env_file:
      - docker-compose.env

volumes:
  psql-data:
  redis-data:
